global using System.Reflection;
global using System.Text.Json;
global using IOLink.NET.Core.Contracts;
global using IOLink.NET.Core.Models;
global using IOLink.NET.Vendors.Ifm;
global using IOLink.NET.Vendors.Ifm.Data;
global using NSubstitute;
global using Shouldly;
global using Xunit;
