name: publish_nuget
description: Publish Nuget Packages
# Were we can define the inputs that our action will accept
inputs:
  nugetApiKey: 
    required: true
    description: The API Key to use to publish the package
  nugetPackageSource:
    required: true  
    description: The Nuget Package Source to publish to
  nugetPackageDirectory: 
    required: true
    description: The directory containing the packages to publish

runs:
  using: "composite"
  steps:

  - name: Publish Nuget Packages 
    shell: bash
    working-directory: ${{ inputs.projectPath }}
    run: |
      for file in ${{ inputs.nugetPackageDirectory }}/*.nupkg; do
        dotnet nuget push $file -k ${{ inputs.nugetApiKey }} -s ${{ inputs.nugetPackageSource }} --skip-duplicate
      done

    