name: CI

on:
  push:
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore ./src

      - name: Build
        run: dotnet build ./src --no-restore

      - name: Test
        run: dotnet test ./src --no-build --verbosity normal

  pack:
    name: Build Nuget Packages 
    runs-on: ubuntu-latest
    needs: build
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - run: mkdir -p $PWD/npks

        - uses: ./.github/actions/build_nuget
          name: Build Nuget Package for Conversion
          with:
            projectPath: ./src/Conversion
            outputDirectory: ../../npks

        - uses: ./.github/actions/build_nuget
          with:
            projectPath: ./src/Device
            outputDirectory: ../../npkgs
        - uses: ./.github/actions/build_nuget
          name: Build Nuget Package for IODD.Parser
          with:
            projectPath: ./src/IODD.Parser
            outputDirectory: ../npkgs

        - uses: ./.github/actions/build_nuget
          name: Build Nuget Package for IODD.Provider
          with:
            projectPath: ./src/IODD.Provider
            outputDirectory: ../../npkgs

        - uses: ./.github/actions/build_nuget
          name: Build Nuget Package for IODD.Resolution
          with:
            projectPath: ./src/IODD.Resolution
            outputDirectory: ../../npkgs

        - uses: ./.github/actions/build_nuget
          name: Build Nuget Package for IODD.Structure
          with:
            projectPath: ./src/IODD.Structure
            outputDirectory: ../../npkgs

        - run: echo $PWD
        - run: ls -la $PWD/npkgs
        - name: Publish Nuget Package for ${{ inputs.projectPath }}
          uses: actions/upload-artifact@v2
          with:
            name: packages
            path: $PWD/npkgs

  publish:
    name: Publish Nuget Packages
    runs-on: ubuntu-latest
    needs: pack
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: packages
          path: ./packages

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - uses: ./.github/actions/publish_nuget
        name: Publish Nuget Package for Conversion
        with:
          nugetApiKey: ${{ secrets.NUGET_API_KEY }}
          nugetPackageSource: ${{ secrets.NUGET_PACKAGE_SOURCE }}
          nugetPackageDirectory: $PWD/packages